version: 2

updates:
  # Python dependencies (server)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "server"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"
    
    # Auto-approve and merge patch updates for known safe packages
    ignore:
      # Ignore major version updates for critical packages that need manual review
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uvicorn"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  # Web frontend dependencies
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "web"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"
    
    # Ignore major updates for framework packages
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Alice Tools dependencies
  - package-ecosystem: "npm"
    directory: "/alice-tools"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "alice-tools"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"

  # NLU Agent dependencies
  - package-ecosystem: "npm"
    directory: "/nlu-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "nlu-agent"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"

  # Tools directory dependencies (debug tools)
  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 3
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "tools"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"

  # Docker dependencies (if using Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 3
    target-branch: "develop"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    reviewers:
      - "@evil"
    assignees:
      - "@evil"
    milestone: "Dependencies"

# Global configuration for auto-merge
# This requires additional GitHub workflow to actually merge
# Create .github/workflows/dependabot-auto-merge.yml for auto-merge logic