# YAML Linting Configuration for Alice AI Assistant
extends: default

rules:
  # Line length - be more permissive for readability
  line-length:
    max: 120
    level: warning

  # Comments - allow comments to start anywhere
  comments:
    min-spaces-from-content: 1

  # Indentation - standard 2-space indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Truthy values - allow yes/no, on/off, etc.
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

  # Document start - not required
  document-start: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  node_modules/
  .next/
  dist/
  build/
  .git/