version: '3.8'

services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"    # Signal server
      - "7881:7881"    # RTC server
    environment:
      - LIVEKIT_CONFIG=/etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
      - ./livekit-config:/etc/livekit
    networks:
      - livekit-network

  # Redis körs redan lokalt på port 6379
  # Använder host network för att komma åt lokal Redis

networks:
  livekit-network:
    driver: bridge