global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alice-voice-gateway"
    static_configs:
      - targets: ["voice-gateway:8001"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: "alice-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s